### ISSUE TITLE
setup dns

### ISSUE THREAD

**Issue by victoredwardocallaghan** [librecore-org/librecore-org.github.io#1]
We need to reconfigure our DNS for our domain as follows:

```
librecore.org.   73  IN  A 192.30.252.153
librecore.org.   73  IN  A 192.30.252.154
```

Additionally, on github's side we need to follow [these instructions](https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site).

**Comment by zamaudio** [comment]
See http://librecore.info
