### ISSUE TITLE
Clarify which nonfree software is included

### ISSUE THREAD

**Issue by Jookia** [librecore-org/librecore-org.github.io#5]
Currently the website has these goals:

"librecore is a distribution of Free/Libre firmware recipes for compiling and generating firmware for devices. The intended targets for the firmware include only those which can be run in total freedom by the user. This means that librecore firmware is distributed as source code, and does not include any binary blobs. The purpose of this project is to push the limits of software freedom in boot firmware."

After talking in IRC, it seems that firmware or binary blobs may be included in specific cases. Clarifying this seems like a good idea to avoid misleading users.

**Comment by victoredwardocallaghan** [comment]
Closing as invalid.

You don't seem to understand the difference between pre-compiled executable code and microcode which isn't pre-compiled executable code.

"binary blob" is just a broad term that is normally associated with pre-compiled executable code for which we do not include.

Sorry but the website does not miss lead you, your understanding miss leads you.

**Comment by Jookia** [comment]
Could you please note it includes microcode? While it's not a binary blob by those standards, it's certainly what something like the FSF looks for in boot firmware.

**Comment by victoredwardocallaghan** [comment]
@Jookia will add a section explaining what microcode _really_ is.

Cheers,

**Comment by Jookia** [comment]
It would be great if you cover these points for x86:

- Microcode hasn't been reverse engineered.
- Code signing prevents modified microcode from being loaded.

Seeing as this issue is closed, could this issue be reopened until it's added?
